spring.application.name=presupuesto-personal

# Base de datos
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=presupuesto_personal;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Puerto
server.port=8080

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=CORREO
spring.mail.password=CONTRASEÑA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true